[load_balancer]
host="0.0.0.0"
port=6170
routes_path="routes.json"
debug=true

[[proxy_services]]
container_label_key="cbl.dev.nginx"
container_label_value="groupA"
container_path = "/"
container_port = 80
container_private = true
container_public_ip = "0.0.0.0"

[[proxy_services]]
container_label_key="cbl.dev.nginx"
container_label_value="groupC"
container_path="/"
container_port = 80
container_private = true
container_public_ip = "0.0.0.0"

[[proxy_services]]
container_label_key="cbl.dev.nginx"
container_label_value="groupB"
container_path = "/app3"
container_port = 80
container_private = true
container_public_ip = "0.0.0.0"

[health_check]
health_check_frequency=1000
update_frequency=1500
parallel_health_check=false