[load_balancer]
host="0.0.0.0"
port=6170

[[proxy_services]]
container_label_key="cbl.dev.nginx"
container_label_value="groupA"
container_path="/api"
container_port=80

[[proxy_services]]
container_label_key="cbl.dev.nginx"
container_label_value="groupA"
container_path="/"
container_port=81

[health_check]
health_check_frequency=15
update_frequency=15
parallel_health_check=false